### ISSUE TITLE
VSCode 1.42.0: Activating extension fernandoescolar.vscode-solution-explorer failed due to an error

### ISSUE THREAD

**Issue by ndotb** [fernandoescolar/vscode-solution-explorer#120]
VS Code "about" info
================
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic

Extension Host Log
===============
```
[2020-02-07 20:54:35.082] [exthost] [error] Activating extension fernandoescolar.vscode-solution-explorer failed due to an error:
[2020-02-07 20:54:35.082] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:107:11)
	at Object.join (path.js:1037:7)
	at new TemplateEngine (/home/ndotb/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.7/out/extension.js:2:29652)
	at new t.SolutionExplorerProvider (/home/ndotb/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.7/out/extension.js:1:102136)
	at t.activate (/home/ndotb/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.7/out/extension.js:1:99594)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:710:141)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:709:810)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:708:960
	at async Promise.all (index 8)
```

When this started happening
======================
It seemed to be working fine until code was updated to 1.42.

**Comment by ndotb** [comment]
# Workaround 

If I save the open folder as a workspace and make code think it's a multi-root workspace, the path provided in the SolutionExplorerProvider constructor is populated and the extension works fine.

### Source Reference

https://github.com/fernandoescolar/vscode-solution-explorer/blob/a8c1cdc87de28990136155712dc25a2f5d65823a/src/SolutionExplorerProvider.ts#L24
