### ISSUE TITLE
Can't create new empty solution

### ISSUE THREAD

**Issue by damirarh** [fernandoescolar/vscode-solution-explorer#21]
Creating a new empty solution doesn't work any more. There's no `No solution found (click to create a new one)` text in the solution explorer pane when I open an empty folder. If I invoke the command from the Command palette, nothing happens.

In the _Log (Window)_ output window, the following error is emitted when I invoke the command:
```
[2018-06-09 09:39:17.479] [renderer3] [error] Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
	at CreateNewSolutionCommand.shouldRun (C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\commands\CreateNewSolutionCommand.js:15:69)
	at CreateNewSolutionCommand.<anonymous> (C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\commands\base\CommandBase.js:14:23)
	at Generator.next (<anonymous>)
	at C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\commands\base\CommandBase.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\commands\base\CommandBase.js:3:12)
	at CreateNewSolutionCommand.run (C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\commands\base\CommandBase.js:13:16)
	at context.subscriptions.push.vscode.commands.registerCommand.item (C:\Users\Damir\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.2.26\out\SolutionExplorerCommands.js:51:21)
	at e._executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:6)
	at e._doInvokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

I can reproduce the issue in VS Code version 1.23.1, 1.24.0 and 1.25.0-insiders.

**Comment by fernandoescolar** [comment]
I have just test it and I can see the "No solution found (click to create a new one)" tree item when I open an empty folder in Windows and in MacOS X. Would you mind to give me more details?

- SO
- vscode version
- your folder content 
- the full path of the folder
- anything relevant with this error

Anyway I have fixed the error when you execute the "Create new empty solution" command out of the solution explorer tree.
