### ISSUE TITLE
cannot read property foreach of undefined

### ISSUE THREAD

**Issue by amro93** [fernandoescolar/vscode-solution-explorer#95]
Create new solution
Add new/or Existing project

Error appears cannot read property foreach of undefined

**Comment by amro93** [comment]
workbench.main.js:sourcemap:2477 Error: Cannot read property 'forEach' of undefined
	at module.exports.parseDocument.t.elements.forEach.e (C:\Users\Amro\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js:2:13540)
	at Array.forEach (<anonymous>)
	at parseDocument (C:\Users\Amro\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js:2:13495)
	at new p (C:\Users\Amro\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js:2:12029)
	at Function.<anonymous> (C:\Users\Amro\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js:1:112609)
	at Generator.next (<anonymous>)
	at o (C:\Users\Amro\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js:1:111208)

**Comment by amro93** [comment]
in file C:\Users\User\.vscode\extensions\fernandoescolar.vscode-solution-explorer-0.3.4\out\extension.js
at line 2, col 13484
replace
t.elements.forEach(e=>{"ItemGroup"===e.name&&e.elements.forEach
with 
t.elements.forEach(e=>{"ItemGroup"===e.name&&e.elements&&e.elements.forEach

**Comment by fernandoescolar** [comment]
#80 duplicate
